theme: jekyll-theme-minimal
title: Guan Xiuxian
description: A first year HKU-SusTech Joint PhD student
show_downloads: false
logo: _includes/selfie.jpg




github:
  is_project_page: false
  is_user_page: true
